### ISSUE TITLE
Error with decimal aspect ratios

### ISSUE THREAD

**Issue by Fruithapje21** [MaxLastBreath/TOTK-mods#108]
Error happens when trying to apply aspect ratios that are not in the format 'int x int'

Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "form.py", line 807, in run_tasks
  File "form.py", line 955, in Create_Mod_Patch
ValueError: invalid literal for int() with base 10: '21.5'

Consider converting str to float instead of int

**Comment by MaxLastBreath** [comment]
Yeah i will fix it later today

**Comment by w3bsite** [comment]
in the new version I get this error:
Exception in thread Thread-3 (run_tasks):
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "form.py", line 803, in run_tasks
  File "form.py", line 949, in Create_Mod_Patch
KeyError: 'aspect ratio'

**Comment by MaxLastBreath** [comment]
Should be fixed @w3bsite
