### ISSUE TITLE
Ration 19,5x9 doesn't generate

### ISSUE THREAD

**Issue by Gustour** [MaxLastBreath/TOTK-mods#116]
### Describe the bug

```bash
Just choose the ratio 19.5 x 5 and the process never ends.
In logs i have that :

Exception in thread Thread-5 (run_tasks):
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "form.py", line 807, in run_tasks
  File "form.py", line 955, in Create_Mod_Patch
ValueError: invalid literal for int() with base 10: '19.5'
```

### Reproduction steps

```bash
Just choose the ratio 19.5 x 5
```

### Additional context

```bash
1.
2.
3.
...
```

### What's your operating system?

Windows 11

**Comment by Gustour** [comment]
Sorry you can mark it as dup of 108

**Comment by MaxLastBreath** [comment]
yesh im aware of this issue, will fix it soon, dw
