### ISSUE TITLE
[Bug]: after instaling this all i have is crash

### ISSUE THREAD

**Issue by fakdasys** [MaxLastBreath/TOTK-mods#121]
### Describe the bug

```bash
i instaleed this "optimazer" and now totk wont run. i tried everything. unistalling this "optimazier" reinstalling ruyjinx nothing deleting temp files for it AND NOTHING WORKS. even fresh isntal with older firmaware dont work. every other game i have works just fine but not totk
```

### Reproduction steps

```bash
install this 
game dont work
cool bro
```

### Additional context

```bash
00:00:00.053 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.061 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.061 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.062 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.063 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.063 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.064 |I| Configuration LogValueChange: PreferredGpu set to: 0x1002_0x731F
00:00:00.065 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.065 |I| Configuration LogValueChange: ScalingFilter set to: Fsr
00:00:00.065 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.067 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.073 |I| Configuration LogValueChange: EnableVsync set to: False
00:00:00.073 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.073 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.073 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.073 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.073 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.073 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.073 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.073 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.074 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.074 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.075 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMapped
00:00:00.075 |I| Configuration LogValueChange: ExpandRam set to: True
00:00:00.075 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.075 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.078 |I| Configuration LogValueChange: MultiplayerMode set to: Disabled
00:00:00.082 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1279
00:00:00.086 |N| Application Print: Operating System: Microsoft Windows 10.0.19045 (X64)
00:00:00.086 |N| Application Print: CPU: AMD Ryzen 5 3600 6-Core Processor ; 12 logical
00:00:00.087 |N| Application Print: RAM: Total 15.9 GiB ; Available 12 GiB
00:00:00.090 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.090 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:11.757 |E| Application : Unhandled exception caught: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\[redacted]\AppData\Roaming\Ryujinx\Config.json'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String, FileMode, FileAccess, FileShare, FileOptions)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1 )
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1)
   at System.IO.Strategies.SyncWindowsFileStreamStrategy..ctor(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream, String, FileMode, FileAccess, FileShare, Int32, FileOptions, Int64, Nullable`1)
   at System.IO.FileStream..ctor(String, FileMode, FileAccess, FileShare, Int32, FileOptions, Int64)
   at System.IO.FileStream..ctor(String, FileMode, FileAccess, FileShare, Int32, FileOptions)
   at System.IO.File.Create(String, Int32, FileOptions)
   at Ryujinx.Common.Utilities.JsonHelper.SerializeToFile[T](String filePath, T value, JsonTypeInfo`1 typeInfo) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Common\Utilities\JsonHelper.cs:line 46
   at Ryujinx.UI.Common.Configuration.ConfigurationFileFormat.SaveConfig(String path) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.UI.Common\Configuration\ConfigurationFileFormat.cs:line 411
   at Ryujinx.Ava.UI.ViewModels.MainWindowViewModel.SaveConfig() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\UI\ViewModels\MainWindowViewModel.cs:line 1680
   at Ryujinx.Ava.UI.Windows.MainWindow.SaveWindowSizePosition() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\UI\Windows\MainWindow.axaml.cs:line 364
   at Ryujinx.Ava.UI.Windows.MainWindow.OnClosing(WindowClosingEventArgs e) in D:\a\Ryujinx\Ryujinx\src\Ryujinx\UI\Windows\MainWindow.axaml.cs:line 475
   at Avalonia.Controls.Window.ShouldCancelClose(WindowClosingEventArgs)
   at Avalonia.Controls.Window.HandleClosing(WindowCloseReason reason)
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr, UInt32, IntPtr, IntPtr)
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
```

### What's your operating system?

Windows 10

**Comment by MaxLastBreath** [comment]
The error you are getting is related to ryujinx ava not finding it's config. Json file. Reinstall ryujinx nothing related to the Optimizer here.
