### ISSUE TITLE
[Bug]: Crash when trying to apply 21.5x9 aspect ratio patch

### ISSUE THREAD

**Issue by brentward** [MaxLastBreath/TOTK-mods#124]
### Describe the bug

```bash
When I try to apply the 21.5x9 aspect ratio patch the optimizer crashes.
I found this while trying to collect data for the playstation UI bug, it seems to be an error trying to use a floating point value in an integer variable.
I get a similar error for 19.5x9
```

### Reproduction steps

```bash
1. Select 21.5x9 aspect ratio
2. Click apply
```

### Additional context

```bash
I get this in the console:

Attempting to start Application.
__SystemINFO__
System: Windows
GPU: NVIDIA GeForce RTX 4080
RAM: 32 GB 6400 MHz and used 38.1%
CPU: 13th Gen Intel(R) Core(TM) i5-13600K

Succesfully loaded api.json.
Found Legacy Emu folder at: C:\Users\brent\AppData\Roaming\yuzu
Detected a Windows based SYSTEM!
a qt-config.ini file found!
V Camera Sensitivity - 1.0
H Camera Sensitivity - 1.0
Time Speed - 1.0
RSDB Heap size - 1.0
Textures Heap size - 1.0
main
Checking for Updates!
No Updates Found. Your app is up to date.
Found Legacy Emu folder at: C:\Users\brent\AppData\Roaming\yuzu
Starting TASKs for Normal Patch..
Legacy.exe is closed, working as expected.
Downloading: UltraCam
Downloaded: UltraCam
starting the search for UI folder link.
switch
Attempting to download Aspect Ratio 21.5-9
Aspect Ratio 21.5-9 FOLDER already exists, continue...
Checking for Settings...
Saving user choices in TOTKOptimizer.ini
User choices saved in Memory,Attempting to write into file.
Successfully written into log file
Starting Mod Creator.
Generating mod at C:\Users\brent\AppData\Roaming\yuzu\load\0100F2C0115B6000
Exception in thread Thread-1 (run_tasks):
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "form.py", line 807, in run_tasks
  File "form.py", line 955, in Create_Mod_Patch
ValueError: invalid literal for int() with base 10: '21.5'
```

### What's your operating system?

Windows 11

**Comment by brentward** [comment]
Even though the optimizer crashes it does download the aspect ratio patch

**Comment by brentward** [comment]
I see this is a duplicate, sorry for not checking better.

**Comment by MaxLastBreath** [comment]
Yep duplicate, sorry been very busy lately

#116
