### ISSUE TITLE
[Bug]: Won't open.

### ISSUE THREAD

**Issue by lsam3457** [MaxLastBreath/TOTK-mods#128]
### Describe the bug

```bash
1. Run Appimage
2. ttkbootstrapper briefly pops up then crashes
...
```

### Reproduction steps

```bash
1. Run Appimage
2. ttkbootstrapper briefly pops up then crashes
...
```

### Additional context

```bash
Error Log:

Attempting to start Application.
__SystemINFO__
System: Linux
GPU: Undetected
RAM: 14 GB  MHz and used 25.8%
CPU: Linux Undetected

Succesfully loaded api.json.
Detected a steamdeck!
Traceback (most recent call last):
  File "run.py", line 17, in <module>
  File "form.py", line 70, in __init__
  File "form.py", line 708, in load_canvas
  File "form.py", line 111, in create_canvas
  File "modules/checkpath.py", line 49, in checkpath
  File "configparser.py", line 713, in read
  File "configparser.py", line 1101, in _read
configparser.MissingSectionHeaderError: File contains no section headers.
file: '/home/deck/.config/yuzu/qt-config.ini', line: 1
'resolution_setup = 2\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 34, in <module>
TypeError: can only concatenate str (not "MissingSectionHeaderError") to str
[14699] Failed to execute script 'run' due to unhandled exception!
```

### What's your operating system?

SteamOS (steam deck)

**Comment by lsam3457** [comment]
Tried to run the exe version though Proton, and got the same result and the same error.

**Comment by MaxLastBreath** [comment]
file: '/home/deck/.config/yuzu/qt-config.ini', line: 1
'resolution_setup = 2\n'

Delete the \n from that file and it will fix itself

**Comment by lsam3457** [comment]
> > file: '/home/deck/.config/yuzu/qt-config.ini', line: 1
> > 'resolution_setup = 2\n'
> 
> Delete the \n from that file and it will fix itself

Done, but the problem still persists.

**Comment by MaxLastBreath** [comment]
Ah gotcha, yeah that's a bug i should take care of, maybe an older release will work ?

**Comment by lsam3457** [comment]
> Ah gotcha, yeah that's a bug i should take care of, maybe an older release will work ?

Works perfectly using 2.0.3 

Thank you kindly for your help.
