### ISSUE TITLE
[Bug]: launcher on steam deck opens but doesn’t run

### ISSUE THREAD

**Issue by Masterchif92** [MaxLastBreath/TOTK-mods#134]
### Describe the bug

```bash
After a steam os upgrade, the Totk app image opens but nothing happens. It worked before the update
```

### Reproduction steps

```bash
1.open appimage 
2.wait before it starts 
3.a window appear and immediately close
4. Nothing happens
```

### Additional context

```bash
Tried older version but nothing works
```

### What's your operating system?

SteamOS (steam deck)

**Comment by IonasElate** [comment]
Same for me ... I thought i was doing something wrong and dobule checkt if the .appimage is executable. it is but nothing happens after dobule clicking. i tried 2.0.5 and 2.0.6.

**Comment by R0CKH0PP3R** [comment]
This is the same on Manjaro Linux too.

The output from the AppImage release is identical on both SteamDeck & my Manjaro desktop.

The logger captures:
```
TIME: 23:09:46,182 - LOGGER - WARNING: The GPU was not detected, nothing to be concerned about. list index out of range
TIME: 23:09:46,184 - LOGGER - INFO: Failed to import wmi, most likely LINUX.
TIME: 23:09:46,184 - LOGGER - INFO: 



Attempting to start Application.
__SystemINFO__
System: Linux
GPU: Undetected
RAM: 14 GB  MHz and used 23.6%
CPU: Linux Undetected

TIME: 23:09:46,270 - root - INFO: Attempting to create API instructions. Sat Jun  8 23:09:46 2024
TIME: 23:09:46,776 - LOGGER - INFO: Attemping to fetch list and dict of zip files.
TIME: 23:09:46,776 - LOGGER - ERROR: Failed to fetch list and dict of zip files. continues...
TIME: 23:09:46,776 - root - ERROR: Couldn't find local api.json data,Application will default to stored api.json data.
TIME: 23:09:46,776 - root - INFO: Loading api.json file..
TIME: 23:09:46,776 - root - INFO: api.json file not found, loading internal data.
```
While the following is printed to the terminal:
```
The GPU was not detected, nothing to be concerned about. list index out of range
Failed to import wmi, most likely LINUX.




Attempting to start Application.
__SystemINFO__
System: Linux
GPU: Undetected
RAM: 14 GB  MHz and used 23.6%
CPU: Linux Undetected

Attemping to fetch list and dict of zip files.
Failed to fetch list and dict of zip files. continues...
Traceback (most recent call last):
  File "modules/json.py", line 107, in <module>
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "modules/json.py", line 81, in load_values_from_json
FileNotFoundError: [Errno 2] No such file or directory: 'json.data/api.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "form.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "configuration/settings.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "modules/json.py", line 188, in <module>
  File "modules/json.py", line 86, in load_values_from_json
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEI0PVAOB/json.data/api.json'
[5486] Failed to execute script 'run' due to unhandled exception!
```
**In both cases, the Linux Zip release produces an AppImage free of these issues.**

**Comment by MaxLastBreath** [comment]
Fixed!
