### ISSUE TITLE
[Bug]: Game crashes after launching totk with medium settings 

### ISSUE THREAD

**Issue by Lchaxlover** [MaxLastBreath/TOTK-mods#145]
### Describe the bug

```bash
1.I have an rtx 4070 super with a ryzen 9 5900x and when I launch the game through the optimizer with medium settings its starts to load the game before it crashes. this the the error message I get: 00:00:27.214 |E| HLE.GuestThread.65 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000002000.
00:00:27.255 |E| HLE.GuestThread.65 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise, Nullable`1 exemptId, Boolean guest) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 349
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 275
   at Ryujinx.Cpu.MemoryEhMeilleure.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\MemoryEhMeilleure.cs:line 65
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 145
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 40
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 62
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1263
   at System.Threading.Thread.StartCallback()
2.what do i do?
3.
...
```

### Reproduction steps

```bash
1.
2.
3.
...
```

### Additional context

```bash
1.
2.
3.
...
```

### What's your operating system?

Windows 10

**Comment by MaxLastBreath** [comment]
Please go through this page : https://github.com/MaxLastBreath/TOTK-mods/wiki/TOTK-OPTIMIZER-WIKI

**Comment by anphex** [comment]
I followed the install and troubleshooting guide
I used recommended settings and the mod was installed with success

RyujinX, latest, developer layout enabled

I tried all patch versions. I trying Suyu too, same result.

Not sure what to do. Can I provide a log or something?
