### ISSUE TITLE
[Bug]: After running the TOTK program, a small window appears and then it crashes.

### ISSUE THREAD

**Issue by Biggulu** [MaxLastBreath/TOTK-mods#155]
I only used Ryujinx and did not use Yuzu.

### Describe the bug

```bash
Describe the bug

The GPU was not detected, nothing to be concerned about. list index out of range
Failed to import wmi, most likely LINUX.


Attempting to start Application.
__SystemINFO__
System: Linux
GPU: Undetected
RAM: 15 GB  MHz and used 26.9%
CPU: Linux Undetected

Succesfully loaded api.json.
Detected a steamdeck!
Traceback (most recent call last):
  File "run.py", line 17, in <module>
  File "form.py", line 74, in __init__
  File "form.py", line 708, in load_canvas
  File "form.py", line 115, in create_canvas
  File "modules/checkpath.py", line 58, in checkpath
  File "configparser.py", line 684, in read
  File "configparser.py", line 1063, in _read
configparser.MissingSectionHeaderError: File contains no section headers.
file: '/home/gamer/.config/yuzu/qt-config.ini', line: 1
'resolution_setup=2\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 36, in <module>
TypeError: can only concatenate str (not "MissingSectionHeaderError") to str
[32214] Failed to execute script 'run' due to unhandled exception!


Operating System: ChimeraOS 46-9
KDE Plasma Version: 6.1.2
KDE Frameworks Version: 6.3.0
Qt Version: 6.7.2
Kernel Version: 6.9.8-sk-chos1-chimeraos-1 (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 5600 6-Core Processor
Memory: 15.5 GiB of RAM
Graphics Processor: AMD Radeon RX 6750 GRE 12GB
Manufacturer: ASUS
```

### Reproduction steps

```bash
1.open appimage 
2.wait before it starts 
3.a window appear and immediately close
4.Nothing happens
```

### Additional context

```bash
Tried 2.0.8 version but nothing works
```

### What's your operating system?

SteamOS (steam deck)

**Comment by MaxLastBreath** [comment]
Go to file: '/home/gamer/.config/yuzu/qt-config.ini'

cntrl + f

'resolution_setup=2\n'

delete "\n" and save. Open again and u should be good, or u can delete the entire file if you want to. It's a bug with your emulator.
