### ISSUE TITLE
AppImage 1.3.2 python error

### ISSUE THREAD

**Issue by MG4vQIs7Fv** [MaxLastBreath/TOTK-mods#17]
When I tried version 1.3.2 I got the following error message.

```
Traceback (most recent call last):
  File "run.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "form.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "modules/canvas.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "configuration/settings.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "modules/scaling.py", line 41, in <module>
  File "modules/scaling.py", line 31, in Auto_SF
UnboundLocalError: cannot access local variable 'h' where it is not associated with a value
[10010] Failed to execute script 'run' due to unhandled exception!
```

I am running Python 3.11.5 on Linux 6.4.12-arch1-1 x86_64.
Version 1.3.1 works for me without issue.

**Comment by MaxLastBreath** [comment]
Hey, temporary workaround would be going into manager_config.ini and under [Settings] Scale = 1.0, thank you for the report.

**Comment by MG4vQIs7Fv** [comment]
Thank you. That worked :-)
