### ISSUE TITLE
[Bug]: Invalid Memory Crash on latest update

### ISSUE THREAD

**Issue by Pokejoejo** [MaxLastBreath/TOTK-mods#179]
### Describe the bug

```bash
Crash seems to be pretty consistent. After 10-20 minutes of usage it crashes back to desktop. Here's what the terminal says:

00:08:37.599 |E| HLE.GuestThread.101 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000019000.
00:08:37.635 |E| HLE.GuestThread.101 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise, Nullable`1 exemptId, Boolean guest) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 349
   at Ryujinx.Cpu.MemoryEhMeilleure.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\MemoryEhMeilleure.cs:line 65
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 145
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 40
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 62
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1263
Unhandled exception. Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise, Nullable`1 exemptId, Boolean guest) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 349
   at Ryujinx.Cpu.MemoryEhMeilleure.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\MemoryEhMeilleure.cs:line 65
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 145
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 40
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 62
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1263
```

### Reproduction steps

```bash
nothing specific is required
```

### What's your operating system?

Windows 11

**Comment by Pokejoejo** [comment]
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at ARMeilleure.Translation.Translator.Execute(ARMeilleure.State.ExecutionContext, UInt64)
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(Ryujinx.Cpu.IExecutionContext, UInt64)
   at Ryujinx.HLE.HOS.ArmProcessContext`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Execute(Ryujinx.Cpu.IExecutionContext, UInt64)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()

this one occasionally pops up as well.

**Comment by FracturedPixels** [comment]
I too have been receiving this error sporadically, sometimes it takes hours other times it can be in the first 5 minutes of loading up.

`Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at ARMeilleure.Translation.Translator.Execute(ARMeilleure.State.ExecutionContext, UInt64)
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(Ryujinx.Cpu.IExecutionContext, UInt64)
   at Ryujinx.HLE.HOS.ArmProcessContext1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Execute(Ryujinx.Cpu.IExecutionContext, UInt64)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()`

**Comment by sleepy2con** [comment]
``00:01:55.199 |T| HLE.GuestThread.81 KernelSvc : SleepThread()
00:01:55.199 |T| HLE.GuestThread.81 KernelSvc : SleepThread(timeout: 0x0000000000E4E1C0)
00:01:55.201 |T| HLE.GuestThread.68 KernelSvc : WaitProcessWideKeyAtomic() = TimedOut
00:01:55.201 |T| HLE.GuestThread.68 KernelSvc : SignalProcessWideKey(address: 0x000000658B839D5C, count: 0x00000001)
00:01:55.201 |T| HLE.GuestThread.68 KernelSvc : SignalProcessWideKey() = Success
00:01:55.201 |T| HLE.GuestThread.68 KernelSvc : SendSyncRequest(handle: 0x0008800D)
00:01:55.201 |T| HLE.OsThread.3 KernelIpc CallCmifMethod: IHidServer: SendVibrationValues
00:01:55.201 |T| HLE.GuestThread.68 KernelSvc : SendSyncRequest() = Success
00:01:55.201 |T| HLE.GuestThread.68 KernelSvc : WaitProcessWideKeyAtomic(mutexAddress: 0x000000658B839D58, condVarAddress: 0x000000658B839D5C, handle: 0x001E8038, timeout: 0x0000000000954D3B)
00:01:55.202 |I| HLE.GuestThread.71 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x00000065a8bec980
	X[01]:	0x00000049e4922dc0 (SP:-0x0260)
	X[02]:	0x000000000d2da9c8 (subsdk1:0x29c8)	=> 
	X[03]:	0x00000000085aa320 (main:0xa6320)	=> 
	X[04]:	0x000000658e69daa8
	X[05]:	0x0000000000000001
	X[06]:	0x00000049e49032d8 (SP:-0xfffffffffffe0778)
	X[07]:	0x00000015c33957e8
	X[08]:	0x00000000000001ff
	X[09]:	0x000000000000ffff
	X[10]:	0x000000000000006a
	X[11]:	0x0000000000000069
	X[12]:	0x000000000000006a
	X[13]:	0x0000000000000001
	X[14]:	0x0000000000000000
	X[15]:	0x0000000000000000
	X[16]:	0x000000000e119308
	X[17]:	0x000000000d542734 (sdk:0x131734)	=> nn::os::detail::InternalCriticalSectionImplByHorizon::Enter()
	X[18]:	0x0000000000000000
	X[19]:	0x00000065a8bec980
	X[20]:	0x00000049e4922dc0 (SP:-0x0260)
	X[21]:	0x00000065a89a0970
	X[22]:	0x000000000bd0b070
	X[23]:	0x0000000002000017
	X[24]:	0xffffffffffffffff
	X[25]:	0x00000000ffffffff
	X[26]:	0x000000000cb84140
	X[27]:	0x000000655cd3a560
	X[28]:	0x00000065a9622140
	FP:	0x00000049e4922b60 (SP)
	LR:	0x000000000d2efd00 (subsdk1:0x17d00)	=> 
	SP:	0x00000049e4922b60 (SP)
	PC:	0x00000000086db960 (main:0x1d7960)	=> 


00:01:55.202 |E| HLE.GuestThread.71 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.
00:01:57.604 |D| UI : [Verbose] [Property] Set 'Color' to '#ff2eeac9' with priority 'LocalValue' (SolidColorBrush #8739743)
00:01:57.604 |D| UI : [Verbose] [Property] Set 'Opacity' to '1' with priority 'LocalValue' (SolidColorBrush #8739743)
00:01:57.604 |D| UI : [Verbose] [Layout] Invalidated measure (TextBlock #16493259)``

I have same problem, I got some logs info, this time is when I load the game and crash,sometimes it will crash after I play a few hours,

**Comment by Ritaku02** [comment]
I'm also getting crashes at complete random. I'm on Switch hardware, however, and thus don't have a crash log. For reference, I was playing with the resolution set to 720p, shadows at 512x, and FPS set to 60.

**Comment by MaxLastBreath** [comment]
Pretty sure i found where the issue is, gonna patch it soon
