### ISSUE TITLE
[Bug]: KeyError: 'aspect ratio'

### ISSUE THREAD

**Issue by Zephirr0xx** [MaxLastBreath/TOTK-mods#190]
### Describe the bug

```bash
Hello ! Here is the bug I get :

Starting TASKs for Normal Patch..
Couldn`t detect if Ryujinx.exe is running.
Downloading: UltraCam
Downloaded: UltraCam
starting the search for UI folder link.
Exception in thread Thread-2 (run_tasks):
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "form.py", line 807, in run_tasks
  File "form.py", line 1094, in DownloadUI
KeyError: 'aspect ratio'
```

### Reproduction steps

```bash
The bug is triggered when I press the 'apply' button on the TOTK optimizer.
```

### Additional context

```bash
t1.
2.
3.
...
```

### What's your operating system?

Windows 11

**Comment by Zephirr0xx** [comment]
> You are using an outdated version of the Optimizer

Okay, Thank you :)

**Comment by MaxLastBreath** [comment]
👍
