### ISSUE TITLE
Stuck on applying patches with Ryujinx flatpak

### ISSUE THREAD

**Issue by chill63** [MaxLastBreath/TOTK-mods#44]
Been having issue since 1.4.0 but just forgot to submit issue. When using Ryujinx as a flatpak on linux, it gets stuck on "Creating Mod ManagerPatch"

Here's the output:

```
The GPU was not detected, nothing to be concerned about. list index out of range




Attempting to start Application.
__SystemINFO__
System: Linux
GPU: Undetected
RAM: 31 GB and used 14.4%


Succesfully loaded api.json.
Detected a Ryujinx flatpak!
Detected a Linux based SYSTEM!
Checking for Updates!
No Updates Found. Your app is up to date.
Detected a Ryujinx flatpak!
Starting TASKs for Normal Patch..
/bin/sh: symbol lookup error: /bin/sh: undefined symbol: rl_trim_arg_from_keyseq
Couldn`t detect if Ryujinx.exe is running.
starting the search for UI folder link.
Selected default Aspect Ratio.
Downloading DFPS: New
Downloaded DFPS: New
Ryujinx Doesn't support custom settings as it, doesn't require them.
Saving user choices in Manager_Config.ini
User choices saved in Memory,Attempting to write into file.
Successfully written into log file
Starting Mod Creator.
Exception in thread Thread-1 (run_tasks):
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "form.py", line 944, in run_tasks
  File "form.py", line 1085, in Create_Mod_Patch
AttributeError: 'Manager' object has no attribute 'ryujinx_config'

```

The log file doesn't seem to contain anything useful since it wrote to the log before attempting to apply the patches.

**Comment by MaxLastBreath** [comment]
Ah i see, I'll look into it today :)

**Comment by MaxLastBreath** [comment]
Should be fixed, let me know if it's still giving issues though! :)
