### ISSUE TITLE
Can't run the tool when there are Unicode (é) characters in executable's path

### ISSUE THREAD

**Issue by tocram1** [MaxLastBreath/TOTK-mods#77]
Hi,

I think have been able to run your tool before on an Nvidia GTX 1650, but now that I use an AMD RX 6750 XT it doesn't boot up...

Here is what comes up in my command prompt:
```
PS C:\Users\Théo\Documents\Backup et Emu Switch> python --version
Python 3.10.11

PS C:\Users\Théo\Documents\Backup et Emu Switch> .\TOTK_Optimizer_1.5.5.exe
The GPU was not detected, nothing to be concerned about. list index out of range




Attempting to start Application.
__SystemINFO__
System: Windows
GPU: Undetected
RAM: 31 GB and used 53.9%


Traceback (most recent call last):
  File "run.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "form.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "modules\canvas.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "configuration\settings.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "modules\json.py", line 60, in <module>
  File "configparser.py", line 713, in read
  File "configparser.py", line 1036, in _read
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 328: invalid continuation byte
[31324] Failed to execute script 'run' due to unhandled exception!
```

So, I tried to run it in another folder path, in `C:\Temp\` as I was suspecting the `é` in my user folder name to be a source of issues... and this is what shows up now:
```
PS C:\Temp> .\TOTK_Optimizer_1.5.5.exe
The GPU was not detected, nothing to be concerned about. list index out of range




Attempting to start Application.
__SystemINFO__
System: Windows
GPU: Undetected
RAM: 31 GB and used 54.0%


Succesfully loaded api.json.
Detected a Windows based SYSTEM!
a qt-config.ini file found!
Checking for Updates!
No Updates Found. Your app is up to date.
```
...and the tool opens up correctly.

My theory is that I was running the tool in another way the last time I opened it up (as I've been messing with Python a lot to use PyTorch on AMD hardware 💀), and maybe the `é` was properly handled or escaped...

**Comment by MaxLastBreath** [comment]
look at #71 duplicate, will try to fix tomorrow when im working on 2.0 or alongside 2.0 rather :)
